### ISSUE TITLE
Issues with extension dropdown

### ISSUE THREAD

**Issue by cg2v** [autolab/Autolab#650]
There are some issues with the recent change to extensions
- When you first pick a user who has no extension, the number of extension days is displayed as NaN
- There seems to be an off-by-one error in the calculation (the number of extension days is one less than I expect)
- perhaps due to the off-by-one error, you can't cancel the extension by re-selecting the original due date (the datepicker considers that date a valid target, but no change is made to the other fields
- after a date is selected, you can't bring the datepicker back up unless you first click outside the field.

**Comment by cg2v** [comment]
Actually, NaN only appears if you click the current due date before clicking any other date, so it's related to the off by one

**Comment by cg2v** [comment]
If you choose a date by typing or picking from the browsers autocomplete and submit the form by pressing return (instead of tab or clicking), then the number of days is not calculated and the submission is rejected

**Comment by zyx-billy** [comment]
Oops thanks for pointing it out. I'll take a look this afternoon. It's probably a problem with the double binding process.

**Comment by zyx-billy** [comment]
It turns out all the off-by-one errors are caused by manually typing in the field (instead of picking from the popup). When the input comes from manually typing, the time associated is the start of that day. Since the actual due time is not at the start of day, the time difference is less than the whole number of days we would expect.
I have updated the code to disregard the time of day (always use start of day) when doing any calculation, so there should be no more rounding errors.

**Comment by zyx-billy** [comment]
The datepicker popup only shows once per focus seems to be part of the plugin, though it does feel weird, so I've added a listener to manually show it whenever a click on the input field happens.

I also updated the listener to monitor for change in the field to prevent the problem with the number of days only gets update once even if the user keeps editing the field after the popup has disappeared. (It used to listen only to popover events). This also solves the problem with the field not updating if the user presses [enter] directly from the input field.

**Comment by zyx-billy** [comment]
I haven't been able to get any NaN yet after the above updates, because the field seems to get filled with the current day the first time it is clicked (no chance of clicking current due date before any other day). Is it possible that it's a browser difference?

**Comment by zyx-billy** [comment]
@cg2v, OK here's the fixes (3795d16).

**Comment by cg2v** [comment]
looks good on my dev server.

NaN can still appear, but I don't think it's a big deal:
 1. Fill in or pick a valid date
 1. click outside the field (or tab)
 1. click in the field (or shift tab)
 1. delete the text

**Comment by zyx-billy** [comment]
OK, that sounds good.
I'll have a solution to NaN ready in a moment. I still can't make NaN appear during normal workflow, but I was able to make it appear by emptying the datepicker field manually. Just need to add a check for validity before calculating dates.

**Comment by zyx-billy** [comment]
@cg2v 
Latest commit: 9d97004963a0af7933cd5b33e4fbfa46168e3a62
So now there's validity checking before converting from new-date to number-of-days. I also changed the number-of-days field to a numbers-only input box, so browser does validation automatically: "submit" button will raise error if input is invalid (Previously invalid input would cause server-side to parse as 0 days)

**Comment by zyx-billy** [comment]
fixed by #652
